name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" # 매일 0시 자동 갱신
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate 3D profile
        uses: yoshi389111/github-profile-3d-contrib@master
        with:
          USERNAME: seongyun4359

      - name: Push to GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generate 3D contribution graph" || echo "No changes to commit"
          git push
